### ISSUE TITLE
Large multisite network causes timeouts when deleting multiple pages

### ISSUE THREAD

**Issue by t-swartz** [websharks/quick-cache#208]
When deleting multiple pages on a large multisite network the max_execution time of 30 seconds is reached and the script times out.

First test was 10 pages, 4 were actually deleted before the timeout occurred. Same issue happens when restoring deleted pages/posts.

Problem does not exist with QC Pro disabled.

**Comment by raamdev** [comment]
I haven't heard back on this issue in several months, so I'm closing this. However, if anyone has anything to add here I'll be happy to consider reopening it.
