### ISSUE TITLE
Homepage not being cached

### ISSUE THREAD

**Issue by CWard74** [websharks/quick-cache#392]
The homepage does not want to cache, it rebuilds the page every time. This happens on multiple installs.

From the response headers:
Cache-Control: "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
Expires: "Thu, 19 Nov 1981 08:52:00 GMT"

**Comment by raamdev** [comment]
@CWard74 It sounds like you might have some other plugin installed that is interfering with Quick Cache. I recommend disabling all plugins except Quick Cache and then testing to see if you're still experiencing this issue.

---

In the future, please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/quick-cache) (for Quick Cache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=quick-cache&request_type=trouble_ticket) (Quick Cache Pro). We try to reserve GitHub for filing bug reports and making feature requests. Thank you! :)

**Comment by palepurple** [comment]
Check wp-config.php and make sure there are no remnants from a previous caching plugin still there (e.g. WPCACHEHOME etc). 

Turn quickcache off, and then back on, and make sure wp-config.php contains 

define('WP_CACHE', TRUE);

near the top....

**Comment by raamdev** [comment]
@palepurple Thanks for the suggestion! 

@CWard74 I haven't heard back from you in a few weeks so I'm going to close this Issue. If you have anything new to report, please do let me know.
