### ISSUE TITLE
Option to reduce number of notifications

### ISSUE THREAD

**Issue by nickcernis** [websharks/quick-cache#396]
Could Quick Cache combine 'detected changes' messages into one update instead of several?

![screen shot on 2015-01-11 at 19-29-23](https://cloud.githubusercontent.com/assets/647669/5696433/5e287f38-99c9-11e4-8934-b48ec250b37f.png)

I like to know that the cache is being rebuilt, but I'd prefer to see one update message along the lines of this:

![edit_post_ _goburo_ _wordpress](https://cloud.githubusercontent.com/assets/647669/5696457/1ed44564-99ca-11e4-92ee-cbcfd741352a.jpg)

Clicking "see details" could reveal the other alerts for those who want more info.

**Comment by raamdev** [comment]
@nickcernis Thanks for the feature request. :) We actually already have an issue open for this. Please see https://github.com/websharks/quick-cache/issues/118.
