### ISSUE TITLE
User Invalidation Not Respecting `qcAC`

### ISSUE THREAD

**Issue by jaswsinc** [websharks/quick-cache#401]
In Quick Cache Pro, the `qcAC` variable is not respected properly whenever a URL contains a query string and a user is currently logged into the site. If a site owner or plugin developer wants to pass `?qcAC=1` to explicitly allow the URL to be cached (even though it contains a query string), this should be honored with user-specific caching also.

Currently, what happens is that `qcAC` is ignored if user caching is enabled and a user is logged into the site with a URL that contains `qcAC=1`. It's an edge case, but it was preventing me from completing a portion of my work to bring ZenCache compat. in AJAX queries performed by WPKBA.

**Comment by raamdev** [comment]
Next release milestone:

- **Bug Fix** (Pro): Fixed a bug where the `qcAC` variable (used to force-enable/disable GET Request caching) was not respected properly whenever a URL contained a query string and a user was currently logged into the site. Props @jaswsinc. See [#401](https://github.com/websharks/quick-cache/issues/401).

**Comment by raamdev** [comment]
The fixes applied from this issue have been released today with v150129:

- **Bug Fix** (Pro): Fixed a bug where the `qcAC` variable (used to force-enable/disable GET Request caching) was not respected properly whenever a URL contained a query string and a user was currently logged into the site. Props @jaswsinc. See [#401](https://github.com/websharks/quick-cache/issues/401).

See the [v150129 announcement post](http://www.websharks-inc.com/post/quick-cache-v150129-now-available/).

---

This issue will now be locked to further updates. If you have something to add related to this Issue, please open a new GitHub Issue and mention this one (#401).
