### ISSUE TITLE
Issues with php 5.4 and nginx

### ISSUE THREAD

**Issue by Danjavia** [websharks/quick-cache#403]
When the page loads under this development environment, the site sends lots of ocacional call_user_callback errors.

I appreciate your help.

**Comment by raamdev** [comment]
@Danjavia Could you please provide us with some more details?

- A copy of the error messages you're receiving
- Information about specific software versions you're running: Quick Cache, PHP, WordPress, Nginx
- Steps to reproduce the error you're seeing (i.e., what do you do to recreate this issue on your dev site?)

**Comment by Danjavia** [comment]
Sorry, we fix the issue, The problems was occur in our server. So many thanks ;)

**Comment by raamdev** [comment]
@Danjavia Thank you for the update. I'm glad to hear you solved this. :-)
