### ISSUE TITLE
Upgrade error plugin quick-cache-pro/quick-cache-pro.inc.php on line 917

### ISSUE THREAD

**Issue by swissexcon** [websharks/quick-cache#406]
Hi, on last upgrade we got this error during upgrading

wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 917

Thanks for your kind support

**Comment by jaswsinc** [comment]
Thanks for the report! :-)

> wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 917

Was there an error message to go along with this?

**Comment by swissexcon** [comment]
No, just came with this line of text on the update page, after clicking update. but looks like the plugin works

**Comment by raamdev** [comment]
This looks related to the work done as part of #389. 

Here's [`quick-cache-pro.inc.php#L916`](https://github.com/websharks/quick-cache-pro/blob/150129/quick-cache-pro/quick-cache-pro.inc.php#L916)

@swissexcon There should definitely be an error message included with that line; it might've been hidden somehow which would explain why you didn't see it. 

If you'd like to help us track this down so we can fix it before the next update, would you be able to provide us with a temporary admin account on your site? We'll reinstall the previous version of Quick Cache Pro, then do the upgrade again and watch for the error to see if we can catch it. If you'd like to help, you can submit a ticket to provide temporary admin account details privately here: http://wsharks.com/1DnIEzf (link expires in 48 hours).

**Comment by jaswsinc** [comment]
@swissexcon Were you able to find anything more on this? Thanks!

**Comment by raamdev** [comment]
@swissexcon I'm closing this issue as I haven't heard back from you and without a copy of the error, it's impossible to troubleshoot any potential problem here.

If you can get us a copy of the error message, I'll reopen this so we can take a closer look.
