### ISSUE TITLE
Auto-cache doesn't work

### ISSUE THREAD

**Issue by winc4** [websharks/quick-cache#412]
Hi,
I just bought pro version and auto-cache engine doesn't work on my webstie. I use Yoast SEO plugin for sitemap. 
wp-cron working and in server logs I can see this:
108.162.230.113 - - [10/Feb/2015:14:05:02 +0100] "HEAD //sitemap_index.xml/ HTTP/1.1" 200 541 "-" "WordPress/4.1; https://lifewelove.com" US -
108.162.230.113 - - [10/Feb/2015:14:05:03 +0100] "GET //sitemap_index.xml/ HTTP/1.1" 200 1643 "-" "PHP/5.4.37" US -

sitemap is lunched by cron, but pages aren't caching.

Regards,
Sebastian

**Comment by raamdev** [comment]
@winc4 I'm sorry to hear you're having trouble. Please open a Support Ticket for this issue here and we'll help you out: https://www.websharks-inc.com/support/?product=quick-cache&request_type=trouble_ticket
