### ISSUE TITLE
Expires headers issue on Minify js & css

### ISSUE THREAD

**Issue by Codexpart** [websharks/quick-cache#414]
Hi,
Let you know that your quick-cache plugin is awesome. But just have one problem in Expires headers issue. Here is report : http://gtmetrix.com/reports/www.essr.ch/hoj8ewwC
Can you please please help me?
Regards
Asif

**Comment by raamdev** [comment]
@Codexpart This is related to an existing feature request: Leverage browser caching (https://github.com/websharks/quick-cache/issues/134).

In the meantime, what you can do is add the following to your main `.htaccess` file:

```htaccess
# Browser Caching
FileETag MTime Size

<IfModule expires_module>
    ExpiresActive on
    ExpiresDefault "access plus 1 week"
</IfModule>
```

When we do add this as a feature to Quick Cache, you can get an early access by becoming a beta tester. Please sign-up to be a beta tester [here](http://www.websharks-inc.com/r/quick-cache-beta-testers-list/).
